'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabase';
import { getCurrentClinicId } from '../../lib/clinic';
type PoolCase={id:string;treatment_need:string;urgency:string;preferred_india_city:string|null;travel_start:string|null;travel_end:string|null;lead_score:number;created_at:string;us_state:string|null};
type AssignedCase=PoolCase&{full_name:string;email:string|null;phone:string|null;whatsapp:string|null;us_city:string|null;preferred_india_state:string|null;problem_description:string|null;us_estimated_cost:number|null;india_budget:number|null;status:string;assigned_clinic_id:string|null};
export default function NRILeads(){
 const [clinicId,setClinicId]=useState<string|null>(null); const [pool,setPool]=useState<PoolCase[]>([]); const [assigned,setAssigned]=useState<AssignedCase[]>([]); const [status,setStatus]=useState('');
 async function load(){if(!supabase)return;const id=await getCurrentClinicId();setClinicId(id);if(!id)return;const [{data:p,error:pe},{data:a,error:ae}]=await Promise.all([supabase.rpc('get_nri_case_pool',{p_clinic_id:id}),supabase.from('nri_dental_cases').select('*').eq('assigned_clinic_id',id).order('lead_score',{ascending:false})]);if(pe||ae)setStatus((pe||ae)?.message||'Unable to load NRI leads.');setPool((p||[]) as PoolCase[]);setAssigned((a||[]) as AssignedCase[])}
 useEffect(()=>{load()},[]);
 async function claim(id:string){if(!supabase||!clinicId)return;const {error}=await supabase.rpc('claim_nri_case',{p_case_id:id,p_clinic_id:clinicId,p_dentist_id:null});setStatus(error?error.message:'NRI case claimed. Patient contact details are now available.');if(!error)load()}
 return <main className="page"><header className="pageHead"><div><p className="eyebrow">NRI DENTAL GROWTH</p><h1>NRI Dental Leads</h1><p className="muted">Consented U.S.-based enquiries for treatment planning in India.</p></div></header>{status&&<div className="toast">{status}</div>}
 <section className="statsRow"><div><span>Available leads</span><strong>{pool.length}</strong></div><div><span>My leads</span><strong>{assigned.length}</strong></div><div><span>High priority</span><strong>{[...pool,...assigned].filter(x=>x.lead_score>=75).length}</strong></div></section>
 <section className="panel"><div className="panelHead"><div><h3>Available NRI cases</h3><p className="muted">Patient contact information stays private until your clinic claims a case.</p></div></div><div className="requestGrid">
 {pool.length===0?<div className="emptyCalendar">No matching unassigned NRI cases at the moment.</div>:pool.map(x=><article className="requestCard" key={x.id}><div className="matchTop"><strong>{x.treatment_need}</strong><span className="matchScore">{x.lead_score}/100</span></div><div className="requestFacts"><span>🇺🇸 {x.us_state||'USA'}</span><span>🇮🇳 {x.preferred_india_city||'India flexible'}</span><span>📅 {x.travel_start||'Flexible'}{x.travel_end?' → '+x.travel_end:''}</span></div><span className="badge open">{x.urgency}</span><div className="matchActions"><button className="primary small" onClick={()=>claim(x.id)}>Claim lead</button></div></article>)}</div></section>
 <section className="panel"><div className="panelHead"><div><h3>My NRI cases</h3><p className="muted">These patients have consented to contact and case sharing.</p></div></div><div className="requestGrid">
 {assigned.length===0?<div className="emptyCalendar">You have not claimed an NRI case yet.</div>:assigned.map(x=><article className="requestCard" key={x.id}><div className="matchTop"><strong>{x.full_name}</strong><span className="matchScore">{x.lead_score}/100</span></div><small>{x.email||''}{x.whatsapp||x.phone?' · '+(x.whatsapp||x.phone):''}</small><div className="requestFacts"><span>🦷 {x.treatment_need}</span><span>🇺🇸 {x.us_city||'USA'} {x.us_state||''}</span><span>🇮🇳 {x.preferred_india_city||'India flexible'}</span><span>📅 {x.travel_start||'Flexible'}{x.travel_end?' → '+x.travel_end:''}</span></div><p>{x.problem_description||'No additional problem description.'}</p>{x.us_estimated_cost&&<small>{'U.S. estimate: $'+x.us_estimated_cost.toLocaleString()}</small>}{x.india_budget&&<small>{'India budget: ₹'+x.india_budget.toLocaleString('en-IN')}</small>}<span className="badge open">{x.status} · {x.urgency}</span></article>)}</div></section>
 </main>}